# Generated by Django 4.2.4 on 2023-08-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Employees',
        ),
        migrations.AlterModelOptions(
            name='daily_attendance',
            options={'verbose_name_plural': 'Daily_attendance'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='logs',
            options={'verbose_name_plural': 'Logs'},
        ),
        migrations.RemoveField(
            model_name='daily_attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='date',
        ),
        migrations.AddField(
            model_name='logs',
            name='conf_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daily_attendance',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='recognition_time',
            field=models.DateTimeField(),
        ),
    ]
