# Generated by Django 4.2.4 on 2023-08-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Employees',
        ),
        migrations.AlterModelOptions(
            name='daily_attendance',
            options={'verbose_name_plural': 'Daily_attendance'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='logs',
            options={'verbose_name_plural': 'Logs'},
        ),
    ]
