# Generated by Django 4.2.4 on 2023-08-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_logs_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_attendance',
            name='date',
        ),
        migrations.AlterField(
            model_name='logs',
            name='recognition_time',
            field=models.DateTimeField(),
        ),
    ]
