# Generated by Django 4.2.4 on 2023-08-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_daily_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='conf_level',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
