# Generated by Django 4.2.4 on 2023-08-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_logs_conf_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_attendance',
            name='conf_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
