# Generated by Django 4.2.4 on 2023-08-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_daily_attendance_conf_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_attendance',
            name='conf_level',
        ),
    ]
