# Generated by Django 4.2.4 on 2023-08-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_daily_attendance_conf_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_attendance',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
